apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-app
  namespace: notejam-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: notejam-app
  template:
    metadata:
      labels:
        app: notejam-app
    spec:
      containers:
      - name: notejam-app
        image: soumya2223/node:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
