apiVersion: v1
kind: Service
metadata:
   name: notejam-app
   namespace: notejam-app
   annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
   selector:
       app: notejam-app
   ports:
    - protocol: TCP
      port: 3000
   type: LoadBalancer
